/**
 * API contract tests.
 *
 * These tests validate that the frontend's expected data shape matches the
 * backend's Pydantic-generated JSON schema.  If the backend changes a field
 * name, adds a required field, or changes a type, these tests will fail.
 *
 * The contract JSON schema is generated by: uv run python scripts/generate_types.py
 */

import * as contract from '../../../../schemas/api-contract.json';

// ── Helpers ──────────────────────────────────────────────────────────────

/**
 * Extract property names from a JSON schema object.
 */
function getSchemaProperties(schema: Record<string, unknown>): string[] {
  const props = schema.properties as Record<string, unknown> | undefined;
  return props ? Object.keys(props) : [];
}

/**
 * Extract required field names from a JSON schema object.
 */
function getRequiredFields(schema: Record<string, unknown>): string[] {
  return (schema.required as string[]) || [];
}

/**
 * Resolve a $ref to a definition within a schema.
 */
function resolveDef(schema: Record<string, unknown>, refName: string): Record<string, unknown> {
  const defs = schema.$defs as Record<string, Record<string, unknown>> | undefined;
  return defs?.[refName] ?? {};
}

// ── Contract Tests ───────────────────────────────────────────────────────

describe('API contract: schedule response', () => {
  const scheduleSchema = contract.schedule as Record<string, unknown>;

  it('has a "games" array field', () => {
    const props = getSchemaProperties(scheduleSchema);
    expect(props).toContain('games');
  });

  it('"games" is required', () => {
    const required = getRequiredFields(scheduleSchema);
    expect(required).toContain('games');
  });
});

describe('API contract: game schema', () => {
  const gameSchema = contract.game as Record<string, unknown>;

  it('has all required fields the frontend depends on', () => {
    const required = getRequiredFields(gameSchema);
    expect(required).toContain('id');
    expect(required).toContain('eventId');
    expect(required).toContain('sport');
    expect(required).toContain('homeTeam');
    expect(required).toContain('awayTeam');
    expect(required).toContain('status');
    expect(required).toContain('startTime');
    expect(required).toContain('network');
  });

  it('has all properties the frontend reads', () => {
    const props = getSchemaProperties(gameSchema);
    const expectedProps = [
      'id', 'eventId', 'sport', 'homeTeam', 'awayTeam', 'status',
      'startTime', 'endTime', 'network', 'homeScore', 'awayScore',
      'venue', 'venueCity', 'venueState', 'quarter', 'timeRemaining', 'odds',
    ];
    for (const prop of expectedProps) {
      expect(props).toContain(prop);
    }
  });

  it('homeScore and awayScore are integer|null (not required)', () => {
    const required = getRequiredFields(gameSchema);
    expect(required).not.toContain('homeScore');
    expect(required).not.toContain('awayScore');

    const props = (gameSchema.properties as Record<string, unknown>);
    const homeScore = props.homeScore as Record<string, unknown>;
    const anyOf = homeScore.anyOf as Array<Record<string, unknown>>;
    const types = anyOf.map((v: Record<string, unknown>) => v.type);
    expect(types).toContain('integer');
    expect(types).toContain('null');
  });
});

describe('API contract: team schema', () => {
  const gameSchema = contract.game as Record<string, unknown>;
  const teamSchema = resolveDef(gameSchema, 'TeamSchema');

  it('has all properties the frontend reads', () => {
    const props = getSchemaProperties(teamSchema);
    const expectedProps = ['id', 'name', 'abbreviation', 'logo', 'record', 'conferenceRecord', 'conference', 'rank'];
    for (const prop of expectedProps) {
      expect(props).toContain(prop);
    }
  });

  it('name and abbreviation are required', () => {
    const required = getRequiredFields(teamSchema);
    expect(required).toContain('name');
    expect(required).toContain('abbreviation');
  });

  it('rank is integer|null', () => {
    const props = (teamSchema.properties as Record<string, unknown>);
    const rank = props.rank as Record<string, unknown>;
    const anyOf = rank.anyOf as Array<Record<string, unknown>>;
    const types = anyOf.map((v: Record<string, unknown>) => v.type);
    expect(types).toContain('integer');
    expect(types).toContain('null');
  });
});

describe('API contract: odds schema', () => {
  const gameSchema = contract.game as Record<string, unknown>;
  const oddsSchema = resolveDef(gameSchema, 'OddsSchema');

  it('has spread and overUnder', () => {
    const props = getSchemaProperties(oddsSchema);
    expect(props).toContain('spread');
    expect(props).toContain('overUnder');
  });

  it('spread is number|null', () => {
    const props = (oddsSchema.properties as Record<string, unknown>);
    const spread = props.spread as Record<string, unknown>;
    const anyOf = spread.anyOf as Array<Record<string, unknown>>;
    const types = anyOf.map((v: Record<string, unknown>) => v.type);
    expect(types).toContain('number');
    expect(types).toContain('null');
  });
});

describe('API contract: bracket response schema', () => {
  const bracketSchema = contract.bracket as Record<string, unknown>;

  it('has all top-level properties the frontend depends on', () => {
    const props = getSchemaProperties(bracketSchema);
    const expectedProps = ['title', 'year', 'championshipInfo', 'defaultTabSectionId', 'tabs'];
    for (const prop of expectedProps) {
      expect(props).toContain(prop);
    }
  });

  it('title and year are not required (have defaults)', () => {
    const required = getRequiredFields(bracketSchema);
    expect(required).not.toContain('title');
    expect(required).not.toContain('year');
  });

  it('tabs is an array', () => {
    const props = (bracketSchema.properties as Record<string, unknown>);
    const tabs = props.tabs as Record<string, unknown>;
    expect(tabs.type).toBe('array');
  });
});

describe('API contract: bracket tab schema', () => {
  const bracketSchema = contract.bracket as Record<string, unknown>;
  const tabSchema = resolveDef(bracketSchema, 'BracketTabSchema');

  it('has all tab properties the frontend reads', () => {
    const props = getSchemaProperties(tabSchema);
    const expectedProps = ['sectionId', 'label', 'regionCode', 'isEnabled', 'liveCount', 'rounds'];
    for (const prop of expectedProps) {
      expect(props).toContain(prop);
    }
  });

  it('sectionId, label, and regionCode are required', () => {
    const required = getRequiredFields(tabSchema);
    expect(required).toContain('sectionId');
    expect(required).toContain('label');
    expect(required).toContain('regionCode');
  });
});

describe('API contract: bracket game schema', () => {
  const bracketSchema = contract.bracket as Record<string, unknown>;
  const gameSchema = resolveDef(bracketSchema, 'BracketGameSchema');

  it('has all game properties the frontend reads', () => {
    const props = getSchemaProperties(gameSchema);
    const expectedProps = [
      'contestId', 'bracketPositionId', 'gameState', 'contestClock',
      'currentPeriod', 'hasStartTime', 'startTime', 'startTimeEpoch',
      'teams', 'broadcaster',
    ];
    for (const prop of expectedProps) {
      expect(props).toContain(prop);
    }
  });

  it('contestId, bracketPositionId, and gameState are required', () => {
    const required = getRequiredFields(gameSchema);
    expect(required).toContain('contestId');
    expect(required).toContain('bracketPositionId');
    expect(required).toContain('gameState');
  });
});

describe('API contract: bracket team schema', () => {
  const bracketSchema = contract.bracket as Record<string, unknown>;
  const teamSchema = resolveDef(bracketSchema, 'BracketTeamSchema');

  it('has all team properties the frontend reads', () => {
    const props = getSchemaProperties(teamSchema);
    const expectedProps = ['isHome', 'isTop', 'isWinner', 'logoUrl', 'score', 'seed', 'nameShort', 'nameFull'];
    for (const prop of expectedProps) {
      expect(props).toContain(prop);
    }
  });

  it('score is integer|null', () => {
    const props = (teamSchema.properties as Record<string, unknown>);
    const score = props.score as Record<string, unknown>;
    const anyOf = score.anyOf as Array<Record<string, unknown>>;
    const types = anyOf.map((v: Record<string, unknown>) => v.type);
    expect(types).toContain('integer');
    expect(types).toContain('null');
  });
});

describe('API contract: game summary schema', () => {
  const summarySchema = contract.gameSummary as Record<string, unknown>;

  it('has all base game fields plus summary-only fields', () => {
    const props = getSchemaProperties(summarySchema);
    // Base game fields
    expect(props).toContain('id');
    expect(props).toContain('homeTeam');
    expect(props).toContain('venue');
    expect(props).toContain('venueCity');
    expect(props).toContain('venueState');
    // Summary-only fields
    expect(props).toContain('boxScore');
    expect(props).toContain('startingPitchers');
    expect(props).toContain('plays');
    expect(props).toContain('leaders');
  });

  it('summary-only fields are optional (not required)', () => {
    const required = getRequiredFields(summarySchema);
    expect(required).not.toContain('boxScore');
    expect(required).not.toContain('startingPitchers');
    expect(required).not.toContain('plays');
    expect(required).not.toContain('leaders');
  });
});
